title: "数式なし！はじめてのディープラーニング - スマホで動くオセロゲーム開発"
summary: 
  ディープラーニングに興味はあるけれど、数学が苦手でハードルが高い…そんなあなたにぴったりの一冊です！

  本書では数式を一切使わず、GitHubに公開されているコードの解説のみで構成されています。


  【本書でできるようになること】

  本書を完了すれば、自分のプロダクトにAIのモデルを組み込む方法がわかるようになります。

  具体的には、以下2つのステップに分かれます。

  
  ・ディープラーニングを使ったAIモデル構築方法の理解
  
  ・作成したモデルを実際のアプリケーションに組み込む方法の理解


  【利用する技術】

  ・Python/PyTorch

  　・ディープラーニングのモデル作成に使用します

  ・Rust/ONNX

  　・学習データの作成と、モデルをスマホアプリへ組み込むために使用します

  ・C#/Unity

  　・ゲームの作成に使用します


  AIのモデルを作成してゲームとして動かすには、多くの技術要素が必要です。

  本書では、シンプルで最小限のコードにまとめ、わかりやすく解説しています。

  様々な技術を使いこなす楽しさも感じていただければ幸いです。


  【筆者コメント】

  ディープラーニングの学習で、私が一番苦労したのは「数式が頭に入ってこない」「実際に動くコードがない」「そもそも題材が面白くない」といった点でした。
  
  そして、作ったモデルをスマホで動かしてみたかったのですが、その網羅的な解説が見つからず苦労しました。


  この本では、数式を一切使わず、すべて動くコードの解説だけでディープラーニングの仕組みを理解できるようにしました。
  
  題材にはオセロゲームを採用し、学びながら楽しさも感じられる内容にしています。また、作成したモデルをスマホで動かすまでの手順を丁寧に解説し、アプリ開発までの一連の流れをしっかり学べる構成です。


  エンジニアが新しい技術を学ぶ上で、一番の早道は「動くコードに対して手を動かすこと」だと思います。


  この本が、あなたの「ディープラーニングを学んでみたい！」という気持ちを後押しできれば幸いです。

topics: ["ディープラーニング", "ONNX", "Unity", "Rust", "モンテカルロ木探索"]
published: false
price: 1000
chapters:
  - 0_intro
  - 1_1_firstdeeplearning
  - 1_2_firstdeeplearning
  - 2_mnist
  - 3_creating_dataset
  - 4_creating_model
  - 5_unity
  - 6_native_app
  - 7_appendix
  - 999_environment
