title: "数式なし！はじめてのディープラーニング - スマホで動くオセロゲーム開発"
summary: 
  hoge
  - アウェグァおいj＠
  - fuga
topics: ["ディープラーニング", "Onnx", "Unity", "Rust", "モンテカルロ木探索"]
published: false
price: 1000 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - intro
  - environment
  - firstdeeplearning
  - mnist
  - creating_dataset
  - creating_model
  - unity
  - native_app
  - appendix
